FROM ubuntu:16.04

# Install packages needed for building Julia and using emscripten
RUN apt-get update \
 && apt-get install -y build-essential gcc g++ cmake curl gfortran git m4 python xz-utils bzip2 nodejs \
 && ln -s nodejs /usr/bin/node

# Build julia
RUN cd /opt \
 && git clone https://github.com/JuliaLang/julia.git --branch v0.6.0

RUN cd /opt/julia \
 && make -j4 \
 && ln -s /opt/julia/julia /usr/bin/julia

# Get the most recent emsdk
COPY emsdk-portable.tar.gz /

# Set up emscripten -- use 1.37.6 to match LLVM versions with Julia
RUN tar -xvzf emsdk-portable.tar.gz \
 && cd /emsdk-portable \
 && ./emsdk update \
 && ./emsdk install sdk-1.37.6-64bit \
 && ./emsdk activate sdk-1.37.6-64bit \
 && /bin/bash /emsdk-portable/emsdk_env.sh \
 && find /emsdk-portable -name "llvm-nm" -exec ln -s {} /usr/bin/llvm-nm  ";" \
 && find /emsdk-portable -name "emcc" -exec ln -s {} /usr/bin/emcc ";" \
 && find /emsdk-portable -name "emsdk" -exec ln -s {} /usr/bin/emsdk ";"


COPY /webserver setup.jl /

# Right now this has to run every time the server changes which is annoying
RUN julia /setup.jl
