FROM amellnik/codegen_wasm

# Custom stuff for web integration
RUN ln -s nodejs /usr/bin/node

# Install additional Julia libraries we want to let people test here?

# For some reason we need to run julia from within this folder in order to get ExportWebAssembly to work right
COPY /setup.jl /
COPY /webserver /webserver
WORKDIR /libs

# Don't run as root, copy packages over
ENV JULIA_PKGDIR=/home/myuser/.julia/v0.7
RUN useradd -ms /bin/bash myuser \
 && chown -R myuser:myuser /julia/julia \
 && cp -R /root/. /home/myuser \
 && chown -R myuser:myuser /home/myuser
USER myuser
RUN julia -e 'using ExportWebAssembly'


CMD node /webserver/index.js
